### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**
improve

### CODE REVIEW

**Comment by GodGun968** [comment]
#540
It looks like He changed my Simplified Chinese to Traditional Chinese

**Comment by GodGun968** [comment]
some mistakes is the same as mine, Just changed Simplified to Traditional

**Comment by Madis0** [comment]
#540 was found to be machine-translated and has been removed.

**Comment by GodGun968** [comment]
Look carefully, that's my translation

**Comment by GodGun968** [comment]
Where is the content in "Chat Reporting Helper" displayed

**Comment by GodGun968** [comment]
I don't quite understand "others are unsupported", what does it mean in detail?

**Comment by Madis0** [comment]
> Look carefully, that's my translation

I understand that you did the original Simplified Chinese translation, there were just concerns with the translation to Traditional Chinese, which was assumed to be machine translated from your original translation.

> Where is the content in "Chat Reporting Helper" displayed

In 1.19.3, on the hover of the icon near the chatbox, bottom right corner.

> I don't quite understand "others are unsupported", what does it mean in detail?

Mods that have ✏️ are those included in the modpack. Other mods are manually installed by user (if any) and the modpack does not provide any support for them.

**Comment by GodGun968** [comment]
That is not really Chinese Traditional use because "zh_tw" is exactly the dialect of Taiwan

**Comment by Madis0** [comment]
> That is not really Chinese Traditional use because "zh_tw" is exactly the dialect of Taiwan

So do you think #540 was bad or good?

**Comment by GodGun968** [comment]
Not enough good, It doesn't take dialect differences into account.&nbsp;and copied my translation

**Comment by Madis0** [comment]
Got it. It has been removed in https://github.com/Fabulously-Optimized/fabulously-optimized/pull/553 🙂

**Comment by GodGun968** [comment]
I did not find the full text of Chat Reporting Helper, can you provide some screenshots, thanks

**Comment by Madis0** [comment]
Alright, here's a few. I'll merge this PR though, so make a new one for it.

[Wiki instructions are here](https://fabulously-optimized.gitbook.io/modpack/readme/language-support#translating-chat-reporting-helper)

image
image
image

**Comment by GodGun968** [comment]
Got it! I don't have time yet. Translation will come, But not now.

**Pull request merged**
