### PR TITLE
Support Prism Launcher

### PR DESCRIPTION
**Pull request by Madis0**
Together with https://github.com/Fabulously-Optimized/wiki/pull/28, hopefully soon

Also:
- [ ] Change this and the short description for Modrinth:

````
<details>

<p style="font-weight:700;font-size:12px;background-color:#bbdefb;">This installation method is intended for <a style="color:#1e88e5" href="https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions#prism-launcher">Prism Launcher</a>. For MultiMC, <a style="color:#1e88e5" href="https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions#multimc">follow these instructions</a>.</p>

<summary>
<span style="color:white;font-size:1px;">Modrinth downloads are supported for <a style="color:white;pointer-events:none" href="https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions#prism-launcher">Prism Launcher</a>. For other launchers, <a style="color:white;pointer-events:none" href="https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions">follow these instructions</a>.
</span>
</summary>

</details>
````
- [ ] Add the rank/emoji for Discord
   - [ ] Remove tags
- [ ] PR https://github.com/Madis0/prismlauncher.github.io/blob/fo/src/wiki/getting-started/install-of-alternatives.md
- [ ] Update other issues about this, if any

### CODE REVIEW

**Comment by Kichura** [comment]
Will MultiMC role be replaced with PolyMC aswell on discord?

**Comment by osfanbuff63** [comment]
> Will MultiMC role be replaced with PolyMC aswell on discord?

No, it will likely be added but not replaced for sure - we aren't dropping MultiMC support.

**Comment by osfanbuff63** [comment]
> Will MultiMC role be replaced with PolyMC aswell on discord?

I would guess not replaced, but at least added.

**Comment by osfanbuff63** [comment]
With #496, this should be at a minimum on hold.

**Pull request merged**
