### PR TITLE
Disclaimer language note (pt-br)

### PR DESCRIPTION
**Pull request by Panemiko**

### CODE REVIEW

**Comment by RaptaG** [comment]
Why did this even close?

**Comment by Panemiko** [comment]
Sorry. I thought i had opened it twice

**Comment by RaptaG** [comment]
Also, I’d suggest you to use different branches for each change (if you are lazy like me and don’t wanna bother with making new branches each time, just click the edit button from the FO repo, not yours. This will make a new branch in your fork and direct you to the PR making page directly after you commit your changes)

**Comment by Panemiko** [comment]
Sure. This is my first open source contribution so I'm learning. Next time I will create a new branch

**Comment by RaptaG** [comment]
> Sure. This is my first open source contribution so I'm learning. Next time I will create a new branch

Yeah it's ok, thanks for contribution too! Also, I'd suggest you to join [our Discord](https://discord.gg/yxaXtaQqdB). If you want to, you can join us and get a contributor rank (as @Madis0 previously said). Also, you'll be able to contact with the devs, contributors and FO community easier (Sorry for the long replies 😅 btw)

**Comment by Panemiko** [comment]
I just entered. my username is Panem#6362

**Pull request merged**
