### PR TITLE
Rename Resourcepacks to Resource-Packs

### PR DESCRIPTION
**Pull request by RaptaG**
Just a visual improvement

### CODE REVIEW

**Comment by Kichura** [comment]
Sounds better yet at the same time, it doesn't make sense to me personally.

**Comment by Madis0** [comment]
Nah, I even considered "resourcepacks" to have really game-like wording but in the end, decided to capitalize it anyway. Any other changes you suggest?

**Comment by Julienraptor01** [comment]
why put a dash ?
Resource Pack is is think what would be the best

**Comment by Madis0** [comment]
Ah yes, I used spaces in other folders anyway. So I'd accept a spaced name.

**Comment by RaptaG** [comment]
> So I'd accept a spaced name
Alright then, I'll replace the dash. I only added the dash for compatibility reasons

**Review by Kichura — APPROVED** [review]

**Pull request merged**
