### PR TITLE
Add existing issues check checkbox

### PR DESCRIPTION
**Pull request by itsmeboy0**
Most people ignore the message and a required checkbox would most likely make them look over it.

### CODE REVIEW

**Comment by Madis0** [comment]
Hmm. I don't want to add this right now, but I shall keep it open for when I do 😄

**Comment by Madis0** [comment]
Decided against this.

**Comment by itsmeboy0** [comment]
And the reason is?

**Comment by Madis0** [comment]
A checkbox does not specifically make people think twice or make them find the issue more easily. I've done this myself - searched for duplicates, posted an issue, browsed a bit and _then_ found the duplicate that had a slightly different wording.

**Pull request closed without merging**
