### PR TITLE
2nd attempt to make MR zip filename match CF's

### PR DESCRIPTION
**Pull request by RozeFound**
Don't forget to update mmc-export

### CODE REVIEW

**Comment by Madis0** [comment]
image
image

Version number broke :D

**Comment by Madis0** [comment]
As of MMC-export 2.7.2, I still get this error, even though the version number is now right.
image

**Comment by RozeFound** [comment]
Weird

**Comment by RozeFound** [comment]
Oh I found the problem

**Comment by RozeFound** [comment]
2.7.3 MUST fix the problem, it's just me being absent-minded for 3 times in a row.

**Comment by Madis0** [comment]
That problem is fixed, but now I noticed that HoldThatChunk no longer gets added (https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/Modrinth/mmc-export.toml#L16)

How that's related, I don't know. I just know that it works on 2.7.0 without this PR and it doesn't work on 2.7.3 with this PR. 🤷

**Pull request merged**
