### PR TITLE
Update Turkish translation

### PR DESCRIPTION
**Pull request by localfossa**
Added translation for MixinTrace

### CODE REVIEW

**Comment by localfossa** [comment]
I thought it was a wrong translation but it isn't so I reverted it.

**Comment by Madis0** [comment]
But does it fit? It seems a bit long

**Comment by localfossa** [comment]
I shortened it a little. I can't make it shorter.

**Comment by Madis0** [comment]
image
nope

Try to rephrase it:
* Helps developers know why it crashes
* Helps developers find crash reason
* Developers can see possible crash reason
etc

[and please test it out](https://fabulously-optimized.gitbook.io/modpack/readme/language-support#translating-mod-menu-helper) on your machine as well.

**Comment by localfossa** [comment]
> image nope
> 
> Try to rephrase it:
> 
> * Helps developers know why it crashes
> * Helps developers find crash reason
> * Developers can see possible crash reason
>   etc
> 
> [and please test it out](https://fabulously-optimized.gitbook.io/modpack/readme/language-support#translating-mod-menu-helper) on your machine as well.

I tested all of these but it is still long
image

**Comment by localfossa** [comment]
Can't I make something like "Makes it easy to find the cause of crashes"
Turkish of this sentence is "Çökmelerin nedenini bulmayı kolaylaştırır"

English sentence has 42 letters.
Turkish sentence has 41 letters.

**Comment by Madis0** [comment]
> Can't I make something like "Makes it easy to find the cause of crashes" Turkish of this sentence is "Çökmelerin nedenini bulmayı kolaylaştırır" image

yeah, sure

**Comment by localfossa** [comment]
Also I fixed translation of ETF

**Review by Madis0 — APPROVED** [review]

**Pull request merged**
