### PR TITLE
Better shield badges

### PR DESCRIPTION
**Pull request by RaptaG**

### CODE REVIEW

**Comment by RaptaG** [comment]
> I like the logo and font on the new Modrinth badge but not the fact that both badges are smaller and still have inconsistent number and color format...

They are shown on different parts of the page so it's not a big issues I believe..

**Comment by Madis0** [comment]
For now yes, but they are meant to go side-by-side when Modrinth is ready. See https://github.com/Madis0/OneBar#readme

**Comment by RaptaG** [comment]
> Seems like we don't agree on this... You can add Modrinth logo to its badge but I do not want the other changes.

You mean the round badges?

**Comment by Madis0** [comment]
Yes, I mean the round badges and shorter Modrinth text.

**Comment by RaptaG** [comment]
> Yes, I mean the round badges and shorter Modrinth text.

Oh ok, I'll fix them

**Comment by RaptaG** [comment]
Oops, I deleted this branch because of an other PR but I will make a new PR 🔜

**Pull request closed without merging**
