### PR TITLE
[PojavLauncher] Create mixin config file

### PR DESCRIPTION
**Pull request by SolDev69**
Apparently this magical file makes PojavLauncher work

### CODE REVIEW

**Comment by Madis0** [comment]
It doesn't work for you otherwise?

**Comment by SolDev69** [comment]
No it still crashes, this was apparently an option in Sodium 0.1.0 that was removed in 0.2.0, this is how I got sodium to work on 1.16.5.

**Comment by SolDev69** [comment]
Currently testing with Fabulously Optimized

**Comment by Madis0** [comment]
My ANGLE setup continues to work with this, so can't hurt to add it I guess.

**Pull request merged**
